#!/bin/sh

APPID=org.webosinternals.hello
NSRVID=org.webosinternals.hello.node

APPS=/media/cryptofs/apps

[ -d $${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the dbus service
rm -f /var/palm/ls2/services/prv/${NSRVID}.service
rm -f /var/palm/ls2/services/pub/${NSRVID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${NSRVID}.json /var/palm/ls2/roles/pub/${NSRVID}.json

# Stop the service if running
/usr/bin/killall -9 ${NSRVID} || true

exit 0
