#!/bin/sh

APPID=org.webosinternals.tweaks
NSRVID=org.webosinternals.tweaks.prefs

APPS=/media/cryptofs/apps

[ -d $${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the dbus service
rm -f /var/palm/ls2/services/prv/${NSRVID}.service
rm -f /var/palm/ls2/services/pub/${NSRVID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${NSRVID}.json /var/palm/ls2/roles/pub/${NSRVID}.json

# Stop the service if running
/usr/bin/killall -9 tweaks.prefs.js || true
/usr/bin/killall -9 ${NSRVID} || true

# Remove service directory
rm -rf ${NSRVDIR}

# Remove database permissiong file
rm -f /etc/palm/db/permissions/${NSRVID}

exit 0
