#!/bin/sh

SID="org.webosinternals.tweaks.prefs"

APPS="/media/cryptofs/apps"

SDIR="${APPS}/usr/palm/services/${SID}"

# Handle execution as pmPostInstall.script

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the dbus service

rm -f /var/palm/ls2/services/prv/${SID}.json
rm -f /var/palm/ls2/services/pub/${SID}.json

# Remove the ls2 roles

rm -f /var/palm/ls2/roles/prv/${SID}.json
rm -f /var/palm/ls2/roles/pub/${SID}.json

# Install the dbus service

mkdir -p /var/palm/ls2/services/prv /var/palm/ls2/services/pub

cp ${APPS}/usr/palm/services/${SID}/${SID}.service /var/palm/ls2/services/prv/${SID}.service
cp ${APPS}/usr/palm/services/${SID}/${SID}.service /var/palm/ls2/services/pub/${SID}.service

# Install the ls2 roles

mkdir -p /var/palm/ls2/roles/prv /var/palm/ls2/roles/pub

cp ${APPS}/usr/palm/services/${SID}/${SID}.json /var/palm/ls2/roles/prv/${SID}.json
cp ${APPS}/usr/palm/services/${SID}/${SID}.json /var/palm/ls2/roles/pub/${SID}.json

# Stop the JS service if running

/usr/bin/luna-send -n 1 palm://${SID}/__quit '{}'

/usr/bin/ls-control scan-services || true

exit 0
